####Deployment_File
APPLICATION_NAME=forge-plan-gen
NAMESPACE=altus-cody
REPLICAS_CNT=1
REVISIONHISTORY_LIMIT=2
DEPDATE_VAR="{{`date +'%Y-%m-%dT%H:%M:%S%z'`}}"  # Assigns current date-time at deployment
PREFERRED_DURING_SCHEDULING_IGNORED_DURING_EXECUTION_WEIGHT=100
APP_IMAGE_DETAIL=APP_IMAGE_DETAIL=us-central1-docker.pkg.dev/ywmytazy-916j-vtwv-wypu-zt9nkt/altus/forge-plan-gen:dev--2677be99
PULL_POLICY=Always
APP_CONFIG_NAME=prjplan-app-config
APP_SECRET_NAME=prjplan-app-secrets
###
#livenessProbe
LIVENESS_PROBE_ENDPOINT='/' 
LIVENESS_PROBE_PORT=8080
LIVENESS_PROBE_SCHEMA=HTTP
LIVENESS_PROBE_INITIAL_DELAY_SECONDS_PROBE=30
LIVENESS_PROBE_PERIOD_SECONDS_PROBE=10
LIVENESS_PROBE_SUCCESS_THRESHOLD=1
LIVENESS_PROBE_TIMEOUT_SECOND=30
LIVENESS_PROBE_FAILURE_THRESHOLD=3
#readinessProbe
READINESS_PROBE_ENDPOINT='/' 
READINESS_PROBE_PORT=8080
READINESS_PROBE_SCHEMA=HTTP
READINESS_PROBE_INITIAL_DELAY_SECONDS_PROBE=30
READINESS_PROBE_PERIOD_SECONDS_PROBE=10
READINESS_PROBE_SUCCESS_THRESHOLD=1
READINESS_PROBE_TIMEOUT_SECOND=30
READINESS_PROBE_FAILURE_THRESHOLD=3
###
#limits
RESOURCE_LIMITS_CPU='2'
RESOURCE_LIMITS_MEMORY=4Gi
#requests
RESOURCE_REQUESTS_CPU='1'
RESOURCE_REQUESTS_MEMORY='2Gi'
###
TERMINATION_MESSAGE_PATH=/dev/termination-log
TERMINATION_MESSAGE_POLICY=File
DNS_POLICY=ClusterFirst
RESTART_POLICY=Always
SCHEDULER_NAME=default-scheduler
TERMINATION_PERIOD_SECONDS=30
####Service_File
LOAD_BALANCER_TYPE="Internal"
PROTOCAL=TCP
SERVICE_PORT=8080
SERVICE_TARGET_PORT=8080
SERVICE_TYPE=LoadBalancer